export const INDUSTRY_MODULES = {
  consumer_brand: {
    label: "Consumer / brand",
    requiredMetricKeys: [
      "top_two_brand_revenue_concentration",
      "dtc_revenue_mix",
      "international_revenue_mix",
      "leading_brand_growth",
      "second_brand_growth",
      "dtc_revenue_growth",
      "international_revenue_growth",
      "inventory_growth_yoy",
      "share_count_change_yoy",
      "buyback_spend",
      "buyback_average_price",
      "sbc_to_revenue",
    ],
  },
  software_platform: {
    label: "Software / platform",
    requiredMetricKeys: [
      "rd_to_revenue",
      "sbc_to_revenue",
      "capex_to_revenue",
      "cloud_or_subscription_growth",
      "rpo_or_backlog_growth",
      "recurring_revenue_mix",
    ],
  },
  advertising_platform: {
    label: "Advertising / platform",
    requiredMetricKeys: [
      "ad_revenue_growth",
      "rd_to_revenue",
      "sbc_to_revenue",
      "capex_to_revenue",
      "engagement_growth",
      "ai_infrastructure_intensity",
    ],
  },
  financial_bank: {
    label: "Bank / financial",
    requiredMetricKeys: [
      "net_interest_margin",
      "cet1_ratio",
      "efficiency_ratio",
      "net_charge_off_ratio",
      "loan_growth",
      "deposit_growth",
    ],
  },
  industrial_manufacturing: {
    label: "Industrial / manufacturing",
    requiredMetricKeys: [
      "backlog_growth",
      "inventory_growth_yoy",
      "operating_margin",
      "fcf_conversion",
      "capex_to_revenue",
      "share_count_change_yoy",
    ],
  },
  biopharma: {
    label: "Biopharma",
    requiredMetricKeys: [
      "rd_to_revenue",
      "fcf_conversion",
      "payout_ratio",
      "net_debt_to_fcf",
      "share_count_change_yoy",
      "adjusted_eps_guidance_midpoint",
      "top_product_revenue_concentration",
      "patent_expiry_revenue_exposure",
      "pipeline_revenue_replacement",
    ],
    criticalMetricKeys: [
      "adjusted_eps_guidance_midpoint",
      "top_product_revenue_concentration",
      "patent_expiry_revenue_exposure",
      "pipeline_revenue_replacement",
    ],
    minPeerDataCount: 2,
    requireThreeYearValuationHistory: true,
    requirePeerValuation: true,
  },
  healthcare_medtech: {
    label: "Healthcare / medtech",
    requiredMetricKeys: [
      "organic_revenue_growth",
      "gross_margin",
      "rd_to_revenue",
      "fcf_conversion",
      "procedure_or_volume_growth",
      "share_count_change_yoy",
    ],
  },
  transaction_network: {
    label: "Transaction / network",
    requiredMetricKeys: [
      "payment_or_transaction_volume_growth",
      "cross_border_or_market_activity_growth",
      "operating_margin",
      "fcf_conversion",
      "capex_to_revenue",
      "share_count_change_yoy",
    ],
  },
  data_subscription: {
    label: "Data / subscription",
    requiredMetricKeys: [
      "recurring_revenue_growth",
      "retention_or_renewal",
      "operating_margin",
      "fcf_conversion",
      "sbc_to_revenue",
      "capex_to_revenue",
    ],
  },
  healthcare_distribution: {
    label: "Healthcare distribution",
    requiredMetricKeys: [
      "revenue_growth",
      "operating_margin",
      "fcf_conversion",
      "working_capital_intensity",
      "share_count_change_yoy",
      "debt_to_ebitda",
    ],
  },
  industrial_distribution: {
    label: "Industrial distribution",
    requiredMetricKeys: [
      "revenue_growth",
      "gross_margin",
      "inventory_growth_yoy",
      "fcf_conversion",
      "working_capital_intensity",
      "share_count_change_yoy",
    ],
  },
  franchise_consumer: {
    label: "Franchise / consumer",
    requiredMetricKeys: [
      "same_store_sales_growth",
      "unit_growth",
      "franchise_mix",
      "royalty_revenue_growth",
      "debt_to_ebitda",
      "share_count_change_yoy",
    ],
  },
};

export const TICKER_INDUSTRY_MODULE = {
  ADBE: "software_platform",
  DECK: "consumer_brand",
  FDS: "data_subscription",
  GMED: "healthcare_medtech",
  CRM: "software_platform",
  MCK: "healthcare_distribution",
  PFE: "biopharma",
  BLBD: "industrial_manufacturing",
  GOOGL: "advertising_platform",
  META: "advertising_platform",
  MSFT: "software_platform",
  MA: "transaction_network",
  ICE: "transaction_network",
  JPM: "financial_bank",
  BSY: "data_subscription",
  DCI: "industrial_manufacturing",
  AOS: "industrial_manufacturing",
  DPZ: "franchise_consumer",
  ALSN: "industrial_manufacturing",
  POWL: "industrial_manufacturing",
  TILE: "industrial_manufacturing",
  GIC: "industrial_distribution",
  ESQ: "financial_bank",
};

export function industryModuleForTicker(ticker) {
  return TICKER_INDUSTRY_MODULE[String(ticker).toUpperCase()] ?? null;
}
