drop policy if exists "service role manages company metric history" on public.company_metric_history;
create policy "service role manages company metric history" on public.company_metric_history for all to service_role using(true) with check(true);
drop policy if exists "service role manages valuation history" on public.valuation_history;
create policy "service role manages valuation history" on public.valuation_history for all to service_role using(true) with check(true);
drop policy if exists "service role manages company peers" on public.company_peers;
create policy "service role manages company peers" on public.company_peers for all to service_role using(true) with check(true);
drop policy if exists "service role manages peer metric snapshots" on public.peer_metric_snapshots;
create policy "service role manages peer metric snapshots" on public.peer_metric_snapshots for all to service_role using(true) with check(true);
drop policy if exists "service role manages capital allocation history" on public.capital_allocation_history;
create policy "service role manages capital allocation history" on public.capital_allocation_history for all to service_role using(true) with check(true);
drop policy if exists "service role manages research freshness" on public.research_freshness;
create policy "service role manages research freshness" on public.research_freshness for all to service_role using(true) with check(true);
drop policy if exists "service role manages research update plans" on public.research_update_plans;
create policy "service role manages research update plans" on public.research_update_plans for all to service_role using(true) with check(true);
drop policy if exists "service role manages investor checklist rules" on public.investor_checklist_rules;
create policy "service role manages investor checklist rules" on public.investor_checklist_rules for all to service_role using(true) with check(true);
drop policy if exists "service role manages investor checklist results" on public.investor_checklist_results;
create policy "service role manages investor checklist results" on public.investor_checklist_results for all to service_role using(true) with check(true);
drop policy if exists "service role manages research v2 sections" on public.research_v2_sections;
create policy "service role manages research v2 sections" on public.research_v2_sections for all to service_role using(true) with check(true);
